- name: git clone mandala-master-api
  git: repo=git@github.com:manga-data-library/mandala-master-api.git dest={{ application_dir }}/mandala-master-api accept_hostkey=yes
  tags:
    - mandala
    - master-api

- name: activator setup
  shell: ./activator compile
  args:
    chdir: "{{ application_dir }}/mandala-master-api"
  tags:
    - mandala
    - master-api
