- name: install CI server
  hosts: ciservers
  become: yes
  roles:
    - common
    - sbt
    - jenkins
    - flyway
    - fabric

- name: deploy Mandala DDL/DML
  hosts: ciservers
  become: no
  roles:
    - mandala/db
