- name: install tasks for Local Server
  hosts: local
  become: yes
  roles:
    - common
    - sbt
    - gradle
    - jenkins
    - flyway
    - fabric
    - schemaspy
    - schemaspy/mysql
    - nginx
    - nginx/mandala/master-api
    - nginx/schemaspy
    - mysql
    - mysql/mandala
    - play
    - go
    - grpc
    - grpc/go
    
#    # kibana
#    - elasticsearch
#    - elasticsearch/curator
#    - kibana

- name: install tasks for local user and deploy repositories
  hosts: local
  become: no
  roles:
    - ruby
    - mandala/db
    - mandala/master-api
    - mandala/analyze-twitter
    - mandala/tsubuyaki
    - mandala/scripts
