- name: install Local Server
  hosts: local
  become: yes
  roles:
    - common
    - sbt
    - jenkins
    - flyway
    - fabric
    - nginx
    - nginx/mandala/master-api
    - mysql
    - mysql/mandala

- name: deploy repositories
  hosts: local
  become: no
  roles:
    - ruby
    - mandala/db
    - mandala/master-api
    - mandala/analyze-twitter
    - mandala/tsubuyaki
    - mandala/scripts
