- name: install mandala-master-api server
  hosts: master-api
  become: yes
  roles:
    - common
    - sbt
    - nginx
    - nginx/mandala/master-api

- name: deploy mandala-master-api
  hosts: master-api
  become: no
  roles:
    - mandala/master-api
