- name: git clone mandala-analyze-twitter
  git: repo=git@github.com:manga-data-library/mandala-analyze-twitter.git dest={{ application_dir }}/mandala-analyze-twitter accept_hostkey=yes
  tags:
    - mandala
    - analyze-twitter

- name: register to /etc/systemd/system
  template: src=mandala-analyze-twitter.service dest=/etc/systemd/system/mandala-analyze-twitter.service
  tags:
    - mandala
    - analyze-twitter
  when: stage == "production"
